---
openapi: 3.0.0
info:
  version: '2.0'
  title: Release Package REST API
  license:
    name: MIT
servers:
- url: http://{orgId}.salesforce.com/services/apexrest/{namespace}/v2
  variables:
    namespace: 
      default: PDLM
      description: This value should default to PDLM for production environments. 
        For dev environments, provide the namespace to your dev org.
paths:
  '/change/{changeId}':
    get:
      summary: Change (Release Package)
      description: Get a change order's details along with related information such
        as Affected Items, Bills of Materials, Approved Manufacturers Lists, and Attachments.
        This endpoint is useful for integrations with downstream systems such as ERP.
      operationId: getChangeOrder
      tags:
      - change
      parameters:
      - name: changeId
        in: path
        description: Change Id Or Change Number
        required: true
        schema:
          type: string
          format: string
      - name: affectedItems
        in: query
        description: Include affected items including details fields and costing information.
        required: false
        schema:
          type: boolean
          format: boolean
          default: false
      - name: bom
        in: query
        description: Include BOMs for each affected item in the payload, only includes the
          first level. affectedItems parameter must be true.
        required: false
        schema:
          type: boolean
          format: boolean
          default: false
      - name: aml
        in: query
        description: Include AML for each affected item in the payload. affectedItems
          parameter must be true.
        required: false
        schema:
          type: boolean
          format: boolean
          default: false
      - name: attachments
        in: query
        description: Include information about Change attachments. If affectedItems
          is true, Item attachments will also be included.
        required: false
        schema:
          type: boolean
          format: boolean
          default: false
      - name: useXMLexportFieldset
        in: query
        description: Use the XML Export field set to determine which fields will
          be returned in the response. Default is false to return all fields.
        required: false
        schema:
          type: boolean
          format: boolean
          default: false
      - name: page
        in: query
        description: Page number when number of affected items 
        required: false
        schema:
          type: integer
          format: integer
          default: 0
      responses:
        '200':
          description: Change Order details fields. Optionally includes Affected Item,
            BOM, and AML data for downstream system integrations.
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/ReleasePackage'
        '404':
          description: Change Order not found
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/Error'
  '/bom/{itemNumber}':
    get:
      summary: BOM 
      description: Query to return a list of assembly records which represent the full BOM for the 
        given Item.
      operationId: getBom
      tags:
      - Bill of Material
      - BOM
      - Assembly
      parameters:
      - name: itemNumber
        in: path
        description: Item Revision Id or Item Number of assembly to retrieve the BOM for. If Item Id or Item Number is provided, will default to latest released revision or latest revision if there is no released revision.
        required: true
        schema:
          type: string
          format: string
      - name: level
        in: query
        description: Level of BOM to fetch. Defaults to All levels.
        required: false
        schema:
          type: string
          format: string
          default: 'all'
      - name: delta
        in: query
        description: Returns the deltas in the BOM between the latest released revision and previous revision in addition to the BOM.
        required: false
        schema:
          type: boolean
          format: boolean
          default: false
      - name: flatten
        in: query
        description: Returns a list of parts in the assembly without level. Will combine duplicate BOM rows that exist at different levels into a single BOM row.
        required: false
        schema:
          type: boolean
          format: boolean
          default: false
      responses:
        '200':
          description: Bill of Materials for a specified Item
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/Assembly'
        '404':
          description: Change Order not found
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/Error'
components:
  schemas:
    ReleasePackage:
      type: object
      required:
      - id
      - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        affectedItems:
          type: array
          items:
            '$ref': '#/components/schemas/AffectedItem'
        attachments:
          type: array
          items:
            '$ref': '#/components/schemas/Attachment'
        next:
          type: string
          description: URL to retrieve the next page of affected items associated 
            to this release package
    AffectedItem:
      type: object
      required:
      - id
      - name
      properties:
        id:
          type: string
        name:
          type: string
        Custom_Field__c:
          type: string
          description: Placeholder for any custom fields an org may have on the Change__c object.
        bom:
          type: array
          items:
            '$ref': '#/components/schemas/Assembly'
        aml:
          type: array
          items:
            '$ref': '#/components/schemas/Manufacturer'
        attachments:
          type: array
          items:
            '$ref': '#/components/schemas/Document'
    Assembly:
      type: object
      description: Assembly row represented in a BOM. 
      required:
      - id
      - name
      - level
      properties:
        id:
          type: string
          description: Id of the child Item record
        name:
          type: string
          description: Name of the child Item record
        PDLM__Level__c:
          type: string
          description: 'BOM level of assembly row. In the format of 1, 1.1, 2, 2.1, 2.2, 2.2.1'
        Custom_Field__c:
          type: string
          description: Placeholder for any custom fields an org may have on the Assembly__c object.
    Attachment:
      type: object
      description: Attachments added to change, quality or AML records
      required: 
      - id
      properties:
        id:
          type: string
          description: Id of the Attachment (ContentDocument record)
        name:
          type: string
          description: Name of the attachment/file
        versionId:
          type: string
          description: The content version ID associated with the file. This contains
            the file's latest base64 encoded content.
        version:
          type: number
          description: The version number associated with the file
    Document:
      type: object
      description: Document records attached to items
      required:
      - id
      properties:
        id:
          type: string
          description: Id of the Attachment (Document__c) record
        name:
          type: string
          description: Name of the attachment
        PDLM__Document_Version__c:
          type: string
          description: The latest content version ID associated with the attachment.
            This contains the files latest base64 encoded content.
        PDLM__External_Attachment_URL__c:
          type: string
          description: URL of the attachment if applicable.
        Custom_Field__c:
          type: string
          description: Placeholder for any custom fields an org may have on the Document__c object.
    Manufacturer:
      type: object
      description: Manufacturer Part representing AML rows
      required:
      - id
      properties:
        id:
          type: string
          description: Id of the Manufacturer Part record
        name:
          type: string
          description: Name of the Manufacturer Part record
        PDLM__Manufacturer__c:
          type: string
        PDLM__Manufacturer_Name__c:
          type: string
        PDLM__Primary_Key__c:
          type: string
          description: Primary key unique identifier for the Manufacturer Part
            record
        Custom_Field__c:
          type: string
          description: Placeholder for any custom fields an org may have on the Manufacturer_Part__c object.
    Error:
      type: object
      required:
      - code
      - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
